// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn__Rz28-v_mh-8-JejVgIukBIoApdQpU',
    appId: '1:728885537568:web:10bff8e2bba99b3b494545',
    messagingSenderId: '728885537568',
    projectId: 'my-demo-applications',
    authDomain: 'my-demo-applications.firebaseapp.com',
    storageBucket: 'my-demo-applications.appspot.com',
    measurementId: 'G-P0BV315WCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxTN5zAfNCW6Jds40aGKbqR3q6vgaY6rI',
    appId: '1:728885537568:android:e7b417a0a5efee4d494545',
    messagingSenderId: '728885537568',
    projectId: 'my-demo-applications',
    storageBucket: 'my-demo-applications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaZ8sS6V_AdIn5nMF4zjf4AJw3bfDMk3A',
    appId: '1:728885537568:ios:65c2ce8da54e6b9d494545',
    messagingSenderId: '728885537568',
    projectId: 'my-demo-applications',
    storageBucket: 'my-demo-applications.appspot.com',
    iosBundleId: 'com.example.uploadImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaZ8sS6V_AdIn5nMF4zjf4AJw3bfDMk3A',
    appId: '1:728885537568:ios:65c2ce8da54e6b9d494545',
    messagingSenderId: '728885537568',
    projectId: 'my-demo-applications',
    storageBucket: 'my-demo-applications.appspot.com',
    iosBundleId: 'com.example.uploadImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn__Rz28-v_mh-8-JejVgIukBIoApdQpU',
    appId: '1:728885537568:web:a9c96665f1c564d2494545',
    messagingSenderId: '728885537568',
    projectId: 'my-demo-applications',
    authDomain: 'my-demo-applications.firebaseapp.com',
    storageBucket: 'my-demo-applications.appspot.com',
    measurementId: 'G-C1YB0J0E1V',
  );
}
